name: gene-actions
on:
  push:
    branches: [ main, branches ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.10.x'
    - name: Use cmake
      run: cmake --version
